---
name: Integration/Regression

on:                   # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      crs-config:
        required: false
        type: string

env:
  go_ftw_version: "v0.4.7"

jobs:
  modsecurity-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        server: [apache, nginx]
        crs_version: [nightly]

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p crs
          mkdir -p tests/integration
          # Get CRS
          gh release download -R coreruleset/coreruleset -A tar.gz -O - ${{ matrix.crs_version }} | tar -xzf - --strip-components=1 -C crs
          # Get go-ftw
          gh release download -R coreruleset/go-ftw -p 'ftw_*_linux_amd64.tar.gz' -O - ${{ env.go_ftw_version }} | tar -xzf - ftw
          # get latest docker-compose.yml file
          curl -skL https://raw.githubusercontent.com/coreruleset/crs-plugin-test-action/main/tests/integration/docker-compose.yml \
            -o tests/integration/docker-compose.yml
      
      - name: "Start ${{ matrix.server }} "
        env:
          EXTRA_CONF: ${{ inputs.crs-config }}
        run: |
          # create logs directory
          mkdir -p tests/logs/${{ matrix.server }}
          # use crs-config, if any
          echo "$EXTRA_CONF" > /tmp/crs-additional-setup.conf
          # start container
          docker-compose -f tests/integration/docker-compose.yml up -d ${{ matrix.server }}
          # Give some room before next phase
          sleep 2

      - name: "Run plugin tests"
        run: |
          ./ftw check -d tests/regression
          ./ftw run -d tests/regression
        env:
          FTW_LOGFILE: 'tests/logs/${{ matrix.server }}/error.log'
      
      - name: "Tear down tests"
        run: |
          docker-compose -f tests/integration/docker-compose.yml down
